package com.lbins.hmjs.dao;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table EMP.
 */
public class Emp {

    /** Not-null value. */
    private String empid;
    private String mobile;
    private String password;
    private String nickname;
    private String cover;
    private String provinceid;
    private String cityid;
    private String areaid;
    private String rzstate2;
    private String is_use;
    private String dateline;
    private String userId;
    private String channelId;
    private String deviceType;
    private String pname;
    private String cityName;
    private String is_push;
    private String rolestate;
    private String lng;
    private String lat;
    private String yqnum;
    private String topnum;
    private String tjempid;
    private String sign;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient EmpDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Emp() {
    }

    public Emp(String empid) {
        this.empid = empid;
    }

    public Emp(String empid, String mobile, String password, String nickname, String cover, String provinceid, String cityid, String areaid, String rzstate2, String is_use, String dateline, String userId, String channelId, String deviceType, String pname, String cityName, String is_push, String rolestate, String lng, String lat, String yqnum, String topnum, String tjempid, String sign) {
        this.empid = empid;
        this.mobile = mobile;
        this.password = password;
        this.nickname = nickname;
        this.cover = cover;
        this.provinceid = provinceid;
        this.cityid = cityid;
        this.areaid = areaid;
        this.rzstate2 = rzstate2;
        this.is_use = is_use;
        this.dateline = dateline;
        this.userId = userId;
        this.channelId = channelId;
        this.deviceType = deviceType;
        this.pname = pname;
        this.cityName = cityName;
        this.is_push = is_push;
        this.rolestate = rolestate;
        this.lng = lng;
        this.lat = lat;
        this.yqnum = yqnum;
        this.topnum = topnum;
        this.tjempid = tjempid;
        this.sign = sign;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEmpDao() : null;
    }

    /** Not-null value. */
    public String getEmpid() {
        return empid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmpid(String empid) {
        this.empid = empid;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    public String getProvinceid() {
        return provinceid;
    }

    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }

    public String getCityid() {
        return cityid;
    }

    public void setCityid(String cityid) {
        this.cityid = cityid;
    }

    public String getAreaid() {
        return areaid;
    }

    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }

    public String getRzstate2() {
        return rzstate2;
    }

    public void setRzstate2(String rzstate2) {
        this.rzstate2 = rzstate2;
    }

    public String getIs_use() {
        return is_use;
    }

    public void setIs_use(String is_use) {
        this.is_use = is_use;
    }

    public String getDateline() {
        return dateline;
    }

    public void setDateline(String dateline) {
        this.dateline = dateline;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    public String getPname() {
        return pname;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getIs_push() {
        return is_push;
    }

    public void setIs_push(String is_push) {
        this.is_push = is_push;
    }

    public String getRolestate() {
        return rolestate;
    }

    public void setRolestate(String rolestate) {
        this.rolestate = rolestate;
    }

    public String getLng() {
        return lng;
    }

    public void setLng(String lng) {
        this.lng = lng;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getYqnum() {
        return yqnum;
    }

    public void setYqnum(String yqnum) {
        this.yqnum = yqnum;
    }

    public String getTopnum() {
        return topnum;
    }

    public void setTopnum(String topnum) {
        this.topnum = topnum;
    }

    public String getTjempid() {
        return tjempid;
    }

    public void setTjempid(String tjempid) {
        this.tjempid = tjempid;
    }

    public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
